name: build curl
run-name: build curl

on:
    repository_dispatch:
        types: [ dependants ]

env:
    EVENT: curl
    LATEST_TAG: latest
    CURL_NAME: curl
    OWNER: ghcr.io/960018

jobs:

    build:
        strategy:
            matrix:
                arch: [ amd64, arm64 ]
                include:
                    -   arch: amd64
                        os: self-amd64
                    -   arch: arm64
                        os: self-arm64
        runs-on: ${{ matrix.os }}
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: checkout
                uses: actions/checkout@v4
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: mkdir
                run: |
                    mkdir -m 755 --parents curl
            -   name: clone
                run: |
                    clone_repo() {
                        cd curl
                        git clone --single-branch $1 $2
                        cd $2
                        git submodule update --init --force
                        rm -rf .git .github
                        cd ../..
                    }
                    clone_repo https://github.com/curl/curl.git source
                    clone_repo https://github.com/ngtcp2/nghttp3.git nghttp3
                    clone_repo https://github.com/ngtcp2/ngtcp2.git ngtcp2
                    clone_repo https://github.com/wolfSSL/wolfssl.git wolfssl
            -   name: build curl
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ${{ env.CURL_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: ${{ matrix.arch == 'amd64' }}
                    tags: ${{ env.OWNER }}/${{ env.CURL_NAME }}:${{ matrix.arch }}
            -   name: cleanup
                run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./
                    docker builder prune -af

    multiarch:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: multiarch
                run: |
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.CURL_NAME }}:amd64 ${{ env.OWNER }}/${{ env.CURL_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.CURL_NAME }}:${{ env.LATEST_TAG }}
            -   name: dispatch
                uses: peter-evans/repository-dispatch@v3
                with:
                    event-type: ${{ env.EVENT }}
                    token: ${{ secrets.GH_TOKEN }}
                    repository: 960018/docker-images
