name: build php-fpm
run-name: build php-fpm

on:
    repository_dispatch:
        types: [ php-fpm-base ]

env:
    EVENT: php-fpm
    LATEST_TAG: latest
    PHP_NAME: fpm
    OWNER: ghcr.io/960018/php

jobs:

    build:
        runs-on: self-arm64
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: hub login
                uses: docker/login-action@v3
                with:
                    registry: docker.io
                    username: ${{ secrets.DH_USERNAME }}
                    password: ${{ secrets.DH_TOKEN }}
            -   name: checkout
                uses: actions/checkout@v4
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: dependencies
                run: |
                    docker pull ghcr.io/960018/scratch:latest
                    docker pull ghcr.io/960018/php/fpm-base:latest
                    docker pull composer:2
            -   name: clone
                run: |
                    clone_repo() {
                        cd php
                        git clone --single-branch $1 $2
                        cd $2
                        git submodule update --init --force
                    
                        COMMIT_HASH=$(git rev-parse HEAD)
                    
                        rm -rf .git .github
                        cd ../..
                    
                        echo "${2}_commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
                    }
                    clone_repo https://github.com/fork-php/php-src.git source
                    clone_repo https://github.com/fork-php/apcu.git apcu
                    clone_repo https://github.com/fork-php/ext-ds.git ext-ds
                    clone_repo https://github.com/fork-php/igbinary.git igbinary
                    clone_repo https://github.com/fork-php/imagick.git imagick
                    clone_repo https://github.com/fork-php/mediawiki-php-excimer.git mediawiki-php-excimer
                    clone_repo https://github.com/fork-php/msgpack-php.git msgpack-php
                    clone_repo https://github.com/fork-php/pecl-ev.git pecl-ev
                    clone_repo https://github.com/fork-php/pecl-event.git pecl-event
                    clone_repo https://github.com/fork-php/pecl-file_formats-lzf.git pecl-file_formats-lzf
                    clone_repo https://github.com/fork-php/pecl-networking-uuid.git pecl-networking-uuid
                    clone_repo https://github.com/fork-php/php-ext-lz4.git php-ext-lz4
                    clone_repo https://github.com/fork-php/php-ext-zstd.git php-ext-zstd
                    clone_repo https://github.com/fork-php/php-inotify.git php-inotify
                    clone_repo https://github.com/fork-php/php-spx.git php-spx
                    clone_repo https://github.com/fork-php/php_zip.git php_zip
                    clone_repo https://github.com/fork-php/phpredis.git phpredis
                    clone_repo https://github.com/fork-php/simdjson_php.git simdjson_php
            -   name: build php-fpm
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: php-${{ env.PHP_NAME }}.dockerfile
                    push: true
                    no-cache: ${{ github.event.client_payload.no_cache || false }}
                    provenance: true
                    sbom: true
                    tags: |
                        ${{ env.OWNER }}/${{ env.PHP_NAME }}:arm64
                        ${{ env.OWNER }}/${{ env.PHP_NAME }}:${{ env.LATEST_TAG }}
                    build-args: |
                        CACHE_BUSTER=${{ github.run_id }}
            -   name: cleanup
                run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./
                    docker builder prune -af

    dispatch:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: dispatch
                if: ${{ github.event.client_payload.skip_dispatch != true }}
                uses: peter-evans/repository-dispatch@v3
                with:
                    event-type: ${{ env.EVENT }}
                    token: ${{ secrets.GH_TOKEN }}
                    repository: 960018/docker-images
                    client-payload: '{"no_cache": "${{ github.event.client_payload.no_cache || false }}"}'
