name: build php-fpm testing
run-name: build php-fpm testing

on:
    repository_dispatch:
        types: [ php-fpm ]

env:
    EVENT: php-fpm-testing
    LATEST_TAG: latest
    PHP_NAME: fpm-testing
    OWNER: ghcr.io/960018/php

jobs:

    build:
        strategy:
            matrix:
                arch: [ amd64, arm64 ]
                include:
                    -   arch: amd64
                        os: self-amd64
                    -   arch: arm64
                        os: self-arm64
        runs-on: ${{ matrix.os }}
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: checkout
                uses: actions/checkout@v4
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: clone
                run: |
                    clone_repo() {
                        cd php
                        if [[ "$3" == "private" ]]; then
                            # For private repositories, use token authentication
                            REPO_URL="https://${{ secrets.GH_TOKEN }}@${1#https://}"
                            git clone --single-branch "$REPO_URL" $2
                        else
                            # For public repositories, use the URL as is
                            git clone --single-branch $1 $2
                        fi
                        cd $2
                        git submodule update --init --force

                        COMMIT_HASH=$(git rev-parse HEAD)

                        rm -rf .git .github
                        cd ../..

                        echo "${2}_commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
                    }
                    clone_repo https://github.com/fork-php/php-src.git source
                    clone_repo https://github.com/fork-php/pcov.git pcov
                    clone_repo https://github.com/fork-php/xdebug.git xdebug
                    clone_repo https://github.com/ozo2003/aspect.git aspect
            -   name: build php-fpm testing
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: php-${{ env.PHP_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: ${{ matrix.arch == 'amd64' }}
                    tags: ${{ env.OWNER }}/${{ env.PHP_NAME }}:${{ matrix.arch }}
            -   name: cleanup
                run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./
                    docker builder prune -af

    multiarch:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: multiarch
                run: |
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.PHP_NAME }}:amd64 ${{ env.OWNER }}/${{ env.PHP_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.PHP_NAME }}:${{ env.LATEST_TAG }}
            -   name: dispatch
                uses: peter-evans/repository-dispatch@v3
                with:
                    event-type: ${{ env.EVENT }}
                    token: ${{ secrets.GH_TOKEN }}
                    repository: 960018/docker-images
