name: build dependants

on:
    repository_dispatch:
        types: [independent]

env:
    BUN_NAME: bun
    EVENT: dependants
    LATEST_TAG: latest
    OWNER: ghcr.io/960018
    NGINX_NAME: nginx

jobs:

    build:
        strategy:
            matrix:
                arch: [amd64, arm64]
                include:
                    -   arch: amd64
                        os: self-amd64
                    -   arch: arm64
                        os: self-arm64
        runs-on: ${{ matrix.os }}
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: checkout
                uses: actions/checkout@v3
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: build bun
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ${{ env.BUN_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: true
                    tags: ${{ env.OWNER }}/${{ env.BUN_NAME }}:${{ matrix.arch }}
            -   name: build nginx
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ${{ env.NGINX_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: true
                    tags: ${{ env.OWNER }}/${{ env.NGINX_NAME }}:${{ matrix.arch }}
            -   name: cleanup
                run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./

    multiarch:
        runs-on: self-amd64
        needs: [build]
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: multiarch
                run: |
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.BUN_NAME }}:amd64 ${{ env.OWNER }}/${{ env.BUN_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.BUN_NAME }}:${{ env.LATEST_TAG }}
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.NGINX_NAME }}:amd64 ${{ env.OWNER }}/${{ env.NGINX_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.NGINX_NAME }}:${{ env.LATEST_TAG }}
            -   name: dispatch
                uses: peter-evans/repository-dispatch@v3
                with:
                    event-type: ${{ env.EVENT }}
                    token: ${{ secrets.GH_TOKEN }}
                    repository: 960018/docker-images
