name: build independent images

on:
    push:
        branches:
            - "master"

env:
    EVENT: independent
    LATEST_TAG: latest
    OWNER: ghcr.io/960018
    SCRATCH_NAME: scratch
    VALKEY_BASE_NAME: valkey-base
    POSTGRES_NAME: postgres
    POSTGRES_VERSIONS: "13 14 15 16 17"

jobs:

    build:
        strategy:
            matrix:
                arch: [amd64, arm64]
                include:
                    -   arch: amd64
                        os: self-amd64
                    -   arch: arm64
                        os: self-arm64
        runs-on: ${{ matrix.os }}
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: checkout
                uses: actions/checkout@v4
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: build scratch
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ${{ env.SCRATCH_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: true
                    tags: ${{ env.OWNER }}/${{ env.SCRATCH_NAME }}:${{ matrix.arch }}
            -   name: build valkey-base
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ${{ env.VALKEY_BASE_NAME }}.dockerfile
                    push: true
                    no-cache: true
                    provenance: true
                    sbom: true
                    tags: ${{ env.OWNER }}/${{ env.VALKEY_BASE_NAME }}:${{ matrix.arch }}
            -   name: build postgres
                run: |
                    for version in ${{ env.POSTGRES_VERSIONS }}; do
                        docker buildx build \
                            --file ${{ env.POSTGRES_NAME }}.dockerfile \
                            --push \
                            --no-cache \
                            --provenance=true \
                            --sbom=true \
                            --build-arg VERSION=${version} \
                            --tag ${{ env.OWNER }}/${{ env.POSTGRES_NAME }}:${version}-${{ matrix.arch }} \
                            .
                    done
            -   name: cleanup
                run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./

    multiarch:
        runs-on: self-amd64
        needs: [build]
        steps:
            -   name: login
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_TOKEN }}
            -   name: buildkit
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: image=moby/buildkit:master-rootless
            -   name: multiarch
                run: |
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.SCRATCH_NAME }}:amd64 ${{ env.OWNER }}/${{ env.SCRATCH_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.SCRATCH_NAME }}:${{ env.LATEST_TAG }}
                    docker buildx imagetools create ${{ env.OWNER }}/${{ env.VALKEY_BASE_NAME }}:amd64 ${{ env.OWNER }}/${{ env.VALKEY_BASE_NAME }}:arm64 --tag ${{ env.OWNER }}/${{ env.VALKEY_BASE_NAME }}:${{ env.LATEST_TAG }}
                    for version in ${{ env.POSTGRES_VERSIONS }}; do
                        docker buildx imagetools create ${{ env.OWNER }}/${{ env.POSTGRES_NAME }}:${version}-amd64 ${{ env.OWNER }}/${{ env.POSTGRES_NAME }}:${version}-arm64 --tag ${{ env.OWNER }}/${{ env.POSTGRES_NAME }}:${version}
                    done
            -   name: dispatch
                uses: peter-evans/repository-dispatch@v3
                with:
                    event-type: ${{ env.EVENT }}
                    token: ${{ secrets.GH_TOKEN }}
                    repository: 960018/docker-images
